### ISSUE TITLE
config option: close.window.after.delete

### ISSUE THREAD

**Issue by vaniwiki** [dregad/dokuwiki-plugin-deletepagebutton#1]
Self explanatory title

**Comment by dregad** [comment]
Sorry but the specification is not that clear. 

What exactly do you expect to happen after deleting the page when this option is ON ? Close the browser tab ?

**Comment by vaniwiki** [comment]
Yes, that is what I meant... It seemed like a good idea at the time. But I suppose that is not really a necessary or even such a good option after all. I apologise for the disturbance! :)

**Comment by dregad** [comment]
OK, thanks for the feedback.
