### ISSUE TITLE
Allows to delete pages for not authorized users

### ISSUE THREAD

**Issue by KotM** [dregad/dokuwiki-plugin-deletepagebutton#10]
Recently I installed this plugin and most of my pages were removed by internet-crawler. It was happened because group @ALL has "create" restrictions (not "delete"!).

I assume it should be fixed. 

Also could you please advise how to restore latest content, how to perform mass revert? I have no idea except using a backups.

**Comment by Klap-in** [comment]
Does the Revert plugin help here?
It can mass revert changes, not sure how it handles just created pages.
https://www.dokuwiki.org/plugin:revert

**Comment by Klap-in** [comment]
I misread your question. Your question was how to get back mass deleted pages. That is already supported by the revert plugin, a quote from its wiki page: “Tip! If someone has deleted a lot of pages, just hit the “Search” button without entering a search string.”

**Comment by dregad** [comment]
@KotM in Dokuwiki, as I understand it the act of deleting a page is an EDIT operation.

The _delete_ auth level applies only to namespaces, please read https://www.dokuwiki.org/acl. From the _Background Info_ section:

> Note: The delete permission affects media files only. **Pages can be deleted (and restored) by everyone with at least edit permission**. 

I am therefore closing this.
