### ISSUE TITLE
No icon

### ISSUE THREAD

**Issue by fidokomik** [dregad/dokuwiki-plugin-deletepagebutton#2]
I install your plugin by admin page in Docuwiki but no Trash icon is shown.

![Snímek obrazovky pořízený 2020-03-30 15-24-50](https://user-images.githubusercontent.com/4332168/77917866-5cc2f780-729b-11ea-83c9-f7b8495eca76.png)

**Comment by dregad** [comment]
Did you look at the screenshot in the README ? The icon is accessible when viewing the page, not in edit mode.

**Comment by fidokomik** [comment]
Icon is not shown in view mode nor in edit mode. Need you any other info about our Dokuwiki?

**Comment by dregad** [comment]
Please check that you are running _2018-04-22 "Greebo"_ - older versions are not supported.

Also, I only tested with the default _dokuwiki_ template, if you use another one, please specify which.

**Comment by fidokomik** [comment]
Sorry for czech mutation, You will understand I hope.

```
URL stahování:github.com/dregad/dokuwiki-plug…ebutton/zipball/master
Repozitář: github.com/dregad/dokuwiki-plugin-deletepagebutton/
Nainstalovaná verze: 2020-03-14
Poslední aktualizace Mon, 30 Mar 2020 13:19:29 +0000
Poskytuje: Action
Kompatibilní s: "Greebo" (2018-04-22)
------------
DokuWiki Template od  Anika HenkeScreenshot DokuWiki Template
DokuWiki's default template since 2012
Nainstalovaná verze: 2015-07-26
Poskytuje: Template
```

**Comment by dregad** [comment]
Sorry but I'm not able to reproduce.
