### ISSUE TITLE
Confirmation message not working with Bootstrap3 template

### ISSUE THREAD

**Issue by xstable** [dregad/dokuwiki-plugin-deletepagebutton#4]
Thanks for this nice Plugin.

Would be great it there would appear an dialog, which ask" Do you really wan't to remove the page <hereThePath>".
That way it is a little bit saver, if I hit the button accidentally,

BTW, would also be great to be able to move all the history (but only optionally) with the delete-action. Currently I still have  stuff on "?do=revisions"

**Comment by evertonvolpi** [comment]
> Would be great it there would appear an dialog, which ask" Do you really wan't to remove the page ".

@xstable I was having the same issue. What solved the problem for me was changing the plugin script:
[dokuwiki_main_folder]/lib/plugins/deletepagebutton/script.js:

Change line 9 from:
`jQuery('.deletepagebutton a').click(function(e) {`

To:
``jQuery('.deletepagebutton').click(function(e) {``

After that, disable and re-enable the plugin and it should work. Maybe you will also need to restart your server (apache, nginx, etc).

**Comment by xstable** [comment]
thanks @evertonvolpi I'll try it and create an PR for that if it works

**Comment by dregad** [comment]
Thanks for your contribution, but I'd like to understand why this change is necessary, as on the instances where I'm using the plugin, the confirmation pop-up works just fine without it.

This is the markup I'm getting, as you can see there is indeed a `<a>` below .deletepagebutton `<li>`, so the selector works and there is an event associated to the anchor, which is where it should be. 
![image](https://user-images.githubusercontent.com/449891/108129752-e5fb3c80-70ae-11eb-8651-b7d405264347.png)

Is yours different ?

**Comment by evertonvolpi** [comment]
Hey @dregad!

So, for me the class "deletepagebutton" went to the `<a>` tag, and not to its parent `<li>`. 

<img width="434" alt="Screenshot 2021-02-16 174935" src="https://user-images.githubusercontent.com/19538324/108131507-5f7b3680-707f-11eb-940c-89a69d8a9730.png">

**Comment by dregad** [comment]
Which template are you using ?

**Comment by evertonvolpi** [comment]
Bootstrap3

When using the default theme it works exactly like yours. I confess I didn't read the documentation of your plugin to check if this situation is referenced. If it's not, maybe it's worth mentioning it now that we know about it! 
It's a great plugin, I am sure a lot of people will use it.

**Comment by dregad** [comment]
> I didn't read the documentation of your plugin to check if this situation is referenced

It just says that I only ever tested the plugin with the default DokuWiki template.
https://github.com/dregad/dokuwiki-plugin-deletepagebutton/blob/release_2021-01-09/README.md#compatibility

That's the problem with relying on jQuery scripts, it makes the behavior dependent on markup. So the fix proposed in #5 is not valid as it would break the plugin for DokuWiki template. Some logic is required so it works in both cases.

**Comment by dregad** [comment]
Release 2021-02-19 which I just published, should fix this (Bootstrap3 template's specific markup is now taken into consideration when building the jQuery selector used to add the on click event that displays the confirmation message.
